### PR TITLE
Add Foundry for Manual Integration Testing

### PR DESCRIPTION
**Pull request by abdulrabbani00**
This PR imbeds foundry into `vulcanize-geth`. Currently there is only one project under the `foundry/projects` directory. In the future, developers can add smart contract testing using foundry. Or they can simply leverage the local network created using the current project.

### CODE REVIEW

**Review by i-norden — COMMENTED** [review]
This is great! Directions were easy to follow, and based on my limited test run it feels a lot faster than dapptools.

If you can go ahead and fix that linting error, which is left over from me, that'd be nice. Just need to remove `makeLightNode` func in cmd/geth/config.go.

Also we should target this PR to this branch: https://github.com/vulcanize/go-ethereum/tree/v1.10.16-statediff-v3

General workflow for merges and releases goes:

* Feature/dev branch =PR=> Root versioned branch (e.g. 1.10.16-statediff-v2 or 1.10.16-statediff-v3) 
* Root versioned branch =Checkout=> Release branch (e.g. 1.10.16-statediff-2.0.1 or 1.10.16-statediff-3.0.3)
* Cut release off Release branch
* Root versioned branch =PR=> Root branch (aka `statediff`)
Which root versioned branch we maintain parity with on `statediff` is whatever major version we consider canonical at the time.

**Comment by abdulrabbani00** [comment]
@i-norden - Thanks for the insight, I made the updates. Going to let CI/CD run and then hopefully we can merge :D

**Comment by abdulrabbani00** [comment]
@i-norden - Can I get a final sign off please

**Review by i-norden — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
