### PR TITLE
Rebase v1.11.4 wip

### PR DESCRIPTION
**Pull request by ABastionOfSanity**
A new default branch may be necessary.  There are breaking internal changes in this security update.

### CODE REVIEW

**Comment by meththot** [comment]
Thanks

**Comment by meththot** [comment]
Ty

**Review by meththot — COMMENTED** [review]
Tu

**Review by meththot — COMMENTED** [review]
Thsnks

**Review by meththot — COMMENTED** [review]
Thanks

**Review by meththot — COMMENTED** [review]
Thanks

**Review by meththot — COMMENTED** [review]
#341

**Comment by meththot** [comment]
Thnak

**Review by meththot — COMMENTED** [review]
Thanks

**Comment by i-norden** [comment]
?

**Comment by i-norden** [comment]
This isn't the right way to build github activity

**Pull request merged**
